### PR TITLE
Fix arangosync members state inspection

### LINKED ISSUE #950: Member is in invalid state component=deployment deployment=arango
Hello,
I tried to upgrade the Arango Operator from v1.2.7 to v1.2.9 via manifest

https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.9/manifests/arango-crd.yaml
https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.9/manifests/arango-deployment.yaml
https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.9/manifests/arango-deployment-replication.yaml

After applying these yaml files on the k8s cluster one of the two arango operator pods displays some warnings:

2022-04-05T09:33:30Z INF Ensuring labels component=deployment deployment=arango operator-id=dfdjq
2022-04-05T09:33:30Z INF Reconciliation loop took 260.899035ms component=deployment deployment=arango operator-id=dfdjq
2022-04-05T09:33:30Z INF Inspect loop took 2.486048095s component=deployment deployment=arango operator-id=dfdjq
2022-04-05T09:33:30Z DBG ...inspected deployment component=deployment deployment=arango interval=1.265625s operator-id=dfdjq
2022-04-05T09:33:31Z DBG Inspect deployment... component=deployment deployment=arango operator-id=dfdjq
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=AGNT-bynjiaoz operator-id=dfdjq reachable=false reachableError="Get \"https://X.X.X.X:8529/_api/version\": context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=AGNT-w5hfjzen operator-id=dfdjq reachable=false reachableError="context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=CRDN-xkmv5dco operator-id=dfdjq reachable=false reachableError="Get \"https://X.X.X.X:8529/_api/version
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=8nvw4v5s operator-id=dfdjq reachable=false reachableError="context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=7j1jddim operator-id=dfdjq reachable=false reachableError="context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=ptdj3udi operator-id=dfdjq reachable=false reachableError="Get \"https://arango-sync.default.svc
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=AGNT-btaoymqe operator-id=dfdjq reachable=false reachableError="context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=PRMR-e1vtj0tz operator-id=dfdjq reachable=false reachableError="Get \"https://X.X.X.X:8529/_api/version\": context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=CRDN-y5wvurvf operator-id=dfdjq reachable=false reachableError="context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=5afsulz5 operator-id=dfdjq reachable=false reachableError="context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=vc6tqyst operator-id=dfdjq reachable=false reachableError="Get \"https://arango-sync.default.svc
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=mu5pe0eq operator-id=dfdjq reachable=false reachableError="context deadline exceeded"
2022-04-05T09:33:33Z INF Member is in invalid state component=deployment deployment=arango member=PRMR-0ul9jop3 operator-id=dfdjq reachable=false reachableError="Get \"https://X.X.X.X:8529/_api/version\": context deadline exceeded"
2022-04-05T09:33:33Z DBG ServiceMonitor arango-exporter already found, ensuring it is fine. component=deployment deployment=arango operator-id=dfdjq

When I disable the sync in the arango deployment the warnings disappear.
  sync:
    enabled: false

After that I tried to upgrade to v1.2.8 and there where the same warnings. So I did some debugging and saw the Port in the URL (8529) may be wrong...

After reverting to v1.2.7 the warnings gone away.

Thanks

### PR DESCRIPTION
**Pull request by nikita-vanyasin**
- some refactoring performed for image license string definition
- fixed log State.Log function (always logged reachable=false)

Closes #950

### CODE REVIEW

File: pkg/apis/deployment/v1/image_info.go [hunk 1]
```diff
@@ -39,13 +40,17 @@ func (i *ImageInfo) String() string {
...
 	}
 
-	e := "Community"
+	license := []rune(i.License())
+	license[0] = unicode.ToTitle(license[0])
 
+	return fmt.Sprintf("ArangoDB %s %s (%s)", string(license), string(i.ArangoDBVersion), i.Image)
+}
+
+func (i *ImageInfo) License() string {
```
Comment (ajanikow) [inline pkg/apis/deployment/v1/image_info.go:49]: You are now changing public API interface which can break client backward-compatibility

**Review by ajanikow — CHANGES_REQUESTED** [review]

File: pkg/apis/deployment/v1/image_info.go (hunk 1 above)
Comment (nikita-vanyasin) [reply pkg/apis/deployment/v1/image_info.go]: Done. Changes in v1 api reverted.

**Comment by ajanikow** [comment]
@nikita-vanyasin please, fix CI

**Review by ajanikow — APPROVED** [review]
