### PR TITLE
[Bugfix] GT-103 Ensure pod names not too long

### LINKED ISSUE #1013: Long release names may cause coordinators to have invalid metadata.name lengths
Ran into this today in the logs for the operator:

```
2022-06-14T17:29:29Z INF Event(v1.ObjectReference{Kind:"ArangoDeployment", Namespace:"applications", Name:"the-matrix-application-db-instance-arangodb", UID:"23c007a9-4526-4206-b2a5-14c888ae9d5a", APIVersion:"database.arangodb.com/v1", ResourceVersion:"4194222", FieldPath:""}): type: 'Warning' reason: 'Reconcilation Failed' Service creation failed: Service "the-matrix-application-db-instance-arangodb-coordinator-549cznuy" is invalid: metadata.name: Invalid value: "the-matrix-application-db-instance-arangodb-coordinator-549cznuy": must be no more than 63 characters operator-id=6dd65b6djq8c
```

My actual release name is: `the-matrix-application-db-instance`. The appending of `-arangodb-coordinator` + id has put me at 65 characters.

I'll modify my own release name to avoid the issue for now. In looking over the `_helpers` I didn't see "coordinator" anywhere to manage it's name truncation though.

### PR DESCRIPTION
**Pull request by nikita-vanyasin**
Closes #1013

### CODE REVIEW

**Review by jwierzbo — APPROVED** [review]

File: pkg/apis/shared/names.go [hunk 1]
```diff
@@ -43,13 +47,11 @@ func StripArangodPrefix(id string) string {
 
 // FixupResourceName ensures that the given name
 // complies with kubernetes name requirements.
-// If the name is to long or contains invalid characters,
-// if will be adjusted and a hash with be added.
+// If the name is too long or contains invalid characters,
+// it will be adjusted and a hash with be added.
```
Comment (informalict) [inline pkg/apis/shared/names.go:51]: hash with be added -> hash will be added

**Review by informalict — APPROVED** [review]
LGTM. small comment
